repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: '\.html?$'
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: forbid-yaml-extension
        name: Forbid .yaml files (use .yml instead)
        entry: '.yaml files are not allowed. Please use .yml extension instead.'
        language: fail
        files: 'datasets/.*\.yaml$'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: ['--fix']
      - id: ruff-format
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        # octal integers are a pitfall to anyone not intimately familiar with YAML, so disallow them
        # To illustrate the problem: yaml.safe_load('value: 0555567') → {'value': 187255}
        args: ["-d", "{extends: default, rules: {octal-values: {forbid-implicit-octal: true, forbid-explicit-octal: true}, document-start: disable, line-length: disable}}"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        # Don't run isolated but use the activated venv. Not perfect but better than re-declaring all deps here
        language: system
        exclude: |
          (?x)^(
          zavod/zavod/tests|
          contrib/|
          datasets/|
          )
        args: ['--strict']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        name: mypy-datasets
        # Don't run isolated but use the activated venv. Not perfect but better than re-declaring all deps here
        language: system
        files: "datasets/"
        exclude: |
          (?x)^(
          datasets/eu/journal_sanctions|
          datasets/gb/coh|
          datasets/ky/judicial|
          datasets/lt/pep_declarations|
          datasets/ng/join_dots|
          datasets/us/bis_denied|
          datasets/za/wanted
          )
        args: ['--strict', '--explicit-package-bases']
  - repo: local
    hooks:
      - id: zavod-ui-lint
        name: ESLint
        entry: bash -c "cd ui && npx eslint --fix"
        language: system
        files: '^ui/'
        pass_filenames: false
