repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: '\.html?$'
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: forbid-yaml-extension
        name: Forbid .yaml files (use .yml instead)
        entry: '.yaml files are not allowed. Please use .yml extension instead.'
        language: fail
        files: 'datasets/.*\.yaml$'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: ['--fix']
      - id: ruff-format
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        # octal integers are a pitfall to anyone not intimately familiar with YAML, so disallow them
        # To illustrate the problem: yaml.safe_load('value: 0555567') → {'value': 187255}
        args: ["-d", "{extends: default, rules: {octal-values: {forbid-implicit-octal: true, forbid-explicit-octal: true}, document-start: disable, line-length: disable}}"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        # Don't run isolated but use the activated venv. Not perfect but better than re-declaring all deps here
        language: system
        exclude: |
          (?x)^(
          zavod/zavod/tests|
          contrib/|
          datasets/|
          )
        args: ['--strict']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        name: mypy-datasets
        # Don't run isolated but use the activated venv. Not perfect but better than re-declaring all deps here
        language: system
        files: "datasets/"
        exclude: |
          (?x)^(
          datasets/_analysis|
          datasets/_collections|
          datasets/_externals|
          datasets/_global/c4ads_xinjiang|
          datasets/_global/c4ads_xinjiang_mining|
          datasets/_global/ebrd_ineligible|
          datasets/_global/eiti_soe|
          datasets/_global/everypolitician|
          datasets/_global/iso9362_bic|
          datasets/_global/paris_mou_banned|
          datasets/_global/ransomwhere|
          datasets/_global/research|
          datasets/_global/shu_uyghur_companies|
          datasets/_global/thesentry_atlas|
          datasets/_global/un_1718_vessels|
          datasets/_global/un_ga_protocol|
          datasets/_global/un_sc_sanctions|
          datasets/_wikidata|
          datasets/ae|
          datasets/bg/jud_declarations|
          datasets/cn|
          datasets/eu|
          datasets/gb/coh|
          datasets/gb/nca_most_wanted|
          datasets/gb/nca_press_releases|
          datasets/id|
          datasets/in|
          datasets/ky/judicial|
          datasets/lt|
          datasets/my|
          datasets/ng|
          datasets/no/nbim_exclusions|
          datasets/np|
          datasets/ph|
          datasets/qa|
          datasets/ro|
          datasets/rs|
          datasets/sg|
          datasets/si|
          datasets/sk/rpvs|
          datasets/th/designated_person|
          datasets/tw|
          datasets/ua|
          datasets/us/cia_world_leaders|
          datasets/us/sec_pause|
          datasets/us/ice_wanted|
          datasets/us/irs_ffi|
          datasets/us/state_terrorist_exclusion|
          datasets/us/ofac/enforcement_actions|
          datasets/us/ofac/press_releases|
          datasets/us/sec/pause|
          datasets/us/sec/harmed_investors|
          datasets/us/sec/litigation|
          datasets/us/cftc_enforcement_actions|
          datasets/us/occ_enfact|
          datasets/us/ddtc_enforcements|
          datasets/us/nk_jointventures|
          datasets/us/cia_world_factbook|
          datasets/us/fincen_msb|
          datasets/us/fbi_lazarus_crypto|
          datasets/us/sec_litigation_releases|
          datasets/us/dod_chinese_milcorps|
          datasets/us/dc/exclusions|
          datasets/us/fdic_failed_banks|
          datasets/us/hhs_exclusions|
          datasets/us/plural_legislators|
          datasets/us/fed_enforcements|
          datasets/us/trade_csl|
          datasets/us/cbp_forced_labor|
          datasets/us/dhs_uflpa|
          datasets/us/congress|
          datasets/us/bis_denied|
          datasets/us/state_terrorist_orgs|
          datasets/us/fincen_special_measures|
          datasets/us/dea_fugitives|
          datasets/us/ss_wanted|
          datasets/uy|
          datasets/za
          )
        args: ['--strict', '--explicit-package-bases']
  - repo: local
    hooks:
      - id: zavod-ui-lint
        name: ESLint
        entry: bash -c "cd ui && npx eslint --fix"
        language: system
        files: '^ui/'
        pass_filenames: false
