"""resolver and cache tables from nomenklatura

Revision ID: 34d8c5471e64
Revises: f6e4a1f539b1
Create Date: 2026-10-01 11:13:59.292930

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34d8c5471e64"
down_revision: str | Sequence[str] | None = "f6e4a1f539b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache",
        sa.Column("key", sa.Unicode(), nullable=False),
        sa.Column("text", sa.Unicode(), nullable=True),
        sa.Column("dataset", sa.Unicode(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_cache_timestamp"), "cache", ["timestamp"], unique=False)
    op.create_table(
        "resolver",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target", sa.Unicode(length=512), nullable=True),
        sa.Column("source", sa.Unicode(length=512), nullable=True),
        sa.Column("judgement", sa.Unicode(length=14), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("user", sa.Unicode(length=512), nullable=False),
        sa.Column("created_at", sa.Unicode(length=28), nullable=True),
        sa.Column("deleted_at", sa.Unicode(length=28), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resolver_created_at"), "resolver", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_resolver_deleted_at"), "resolver", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_resolver_source"), "resolver", ["source"], unique=False)
    op.create_index(op.f("ix_resolver_target"), "resolver", ["target"], unique=False)
    op.create_index(
        "resolver_judgement_score",
        "resolver",
        [sa.literal_column("judgement"), sa.literal_column("score")],
        unique=False,
    )
    op.create_index(
        "resolver_source_target_uniq",
        "resolver",
        [sa.literal_column("source"), sa.literal_column("target")],
        unique=True,
        sqlite_where=sa.text("deleted_at IS NULL"),
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "resolver_source_target_uniq",
        table_name="resolver",
        sqlite_where=sa.text("deleted_at IS NULL"),
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("resolver_judgement_score", table_name="resolver")
    op.drop_index(op.f("ix_resolver_target"), table_name="resolver")
    op.drop_index(op.f("ix_resolver_source"), table_name="resolver")
    op.drop_index(op.f("ix_resolver_deleted_at"), table_name="resolver")
    op.drop_index(op.f("ix_resolver_created_at"), table_name="resolver")
    op.drop_table("resolver")
    op.drop_index(op.f("ix_cache_timestamp"), table_name="cache")
    op.drop_table("cache")
    # ### end Alembic commands ###
