- title: UN Consolidated Sanctions
  description: >
    The Security Council's set of sanctions serve as the foundation for most
    national sanctions lists.
  slug: un_sc_sanctions
  category: sanctions
  publisher:
    title: United Nations Security Council
    url: 'https://www.un.org/en/sc/'
  url: 'https://www.un.org/sc/suborg/en/sanctions/un-sc-consolidated-list'
  data:
    url: https://scsanctions.un.org/resources/xml/en/consolidated.xml
    format: XML

- title: World Presidents Database
  description: >
    Current world leaders, presidents, prime ministers and dictators.
  slug: worldpresidentsdb
  category: pep
  publisher:
    title: WorldPresidentsDB.com
    url: 'http://www.worldpresidentsdb.com/'
  url: 'http://www.worldpresidentsdb.com/list/current/'

- title: CIA World Leaders
  description: >
    An index of most national-level cabinet members in world governments that
    is publicly maintained by the CIA.
  slug: us_cia_world_leaders
  category: pep
  publisher:
    title: US Central Intelligence Agency
    url: https://www.cia.gov/
  url: https://www.cia.gov/library/publications/resources/world-leaders-1/index.html

- title: SDFM Blacklist
  description: >
    Ukraine's financial intelligence unit publishes this list of sanctioned
    individuals.
  slug: ua_sdfm_blacklist
  category: sanctions
  publisher:
    title: Ukraine State Finance Monitoring Service
    url: http://www.sdfm.gov.ua/
  url: http://www.sdfm.gov.ua/articles.php?cat_id=87&lang=en
  data:
    url: http://www.sdfm.gov.ua/content/file/Site_docs/Black_list/zBlackListFull.xml
    format: XML

- title: Swiss SECO Sanctions/Embargoes
  description: >
    Switzerland manages a sanctions lists with a high degree of detail on the
    individuals that are subject to it's embargoes.
  slug: ch_seco_sanctions
  category: sanctions
  publisher:
    title: "State Secretariat for Economic Affairs (SECO)"
    url: https://www.seco.admin.ch/
  url: https://www.seco.admin.ch/seco/en/home/Aussenwirtschaftspolitik_Wirtschaftliche_Zusammenarbeit/Wirtschaftsbeziehungen/exportkontrollen-und-sanktionen/sanktionen-embargos.html
  data:
    url: https://www.sesam.search.admin.ch/sesam-search-web/pages/downloadXmlGesamtliste.xhtml?lang=en&action=downloadXmlGesamtlisteAction
    format: XML

- title: OFAC Consolidated List
  description: >
    Both parts of the United States' consolidated sanctions list, both the
    specially designated nationals (SDN) and the non-SDN entities published
    by the Office of Foreign Assets Control (OFAC).
  slug: us_ofac
  category: sanctions
  publisher:
    title: US Department of the Treasury
    url: https://www.treasury.gov/
  url: https://www.treasury.gov/resource-center/sanctions/Pages/default.aspx
  data:
    url: https://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/consolidated.aspx
    format: XML

- title: US Denied Persons List
  description: >
    The Bureau of Industry and Security publishes this list of entities which
    are relevant with regards to export controls.
  slug: us_bis_denied
  category: sanctions
  publisher:
    title: US Department of Commerce
    url: https://www.bis.doc.gov/
  url: https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/denied-persons-list
  data:
    url: https://www.bis.doc.gov/dpl/dpl.txt
    format: txt

- title: GB Consolidated List of Targets
  description: >
    The United Kingom's consolidated internation sanctions list.
  slug: gb_hmt_sanctionslist
  category: sanctions
  publisher:
    title: HM Treasury
    url: https://www.gov.uk/
  url: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets
  data:
    url: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets
    format: html

- title: GB Insolvency Disqualified Directors
  description: >
    Individuals which have been disqualified from holding the post of a
    company director in the United Kingdom following a court decision.
  slug: gb_coh_disqualified
  category: crime
  publisher:
    title: The UK Insolvency Service
    url: https://www.insolvencydirect.bis.gov.uk
  url: https://www.insolvencydirect.bis.gov.uk/IESdatabase/viewdirectorsummary-new.asp
  data:
    url: https://www.insolvencydirect.bis.gov.uk/IESdatabase/viewdirectorsummary-new.asp
    format: html

- title: EEAS Consolidated List
  description: >
    As part of the Common Foreign Security Policy thr European Union publishes
    a sanctions list that is implemented by all member states.
  slug: eu_eeas_sanctions
  category: sanctions
  publisher:
    title: European Union External Action Service
    url: https://eeas.europa.eu/
  url: https://eeas.europa.eu/headquarters/headquarters-homepage/423/sanctions-policy_en
  data:
    url: http://ec.europa.eu/external_relations/cfsp/sanctions/list/version4/global/global.xml
    format: XML

- title: Kyrgyz FIU National List
  description: >
    A simple list of sanctioned individuals and entities published by the
    Kyrgyz' State Financial Intelligence Service.
  slug: kg_fiu_national
  category: sanctions
  publisher:
    title: State Financial Intelligence Service
    url: https://fiu.gov.kg/
  url: https://fiu.gov.kg/sked/1?language=ru
  data:
    url: http://fiu.gov.kg/uploads/595c5fd1ea663.xml
    format: xml

- title: INTERPOL Red Notices
  description: >
    International arrest warrants published by INTERPOL with a view to
    extradition of the wanted individuals.
  slug: interpol_red_notices
  category: crime
  publisher:
    title: Interpol
    url: https://www.interpol.int/
  url: https://www.interpol.int/INTERPOL-expertise/Notices
  data:
    url: https://www.interpol.int/INTERPOL-expertise/Notices
    format: xml

- title: Every Politician
  description: >
    An index of all national members of parliament in the world. This version
    only includes individuals active within the past 15 years.
  slug: everypolitician
  category: pep
  publisher:
    title: MySociety (UK Citizens Online Democracy)
    url: http://everypolitician.org
  url: http://everypolitician.org
  data:
    url: https://github.com/everypolitician/everypolitician-data/raw/master/countries.json
    format: JSON

- title: EU Members of Parliament
  description: >
    A set of all the members of the European Union parliament, which are
    elected by member state.
  slug: eu_meps
  category: pep
  publisher:
    title: European Parliament
    url: http://www.europarl.europa.eu/
  url: http://www.europarl.europa.eu/meps/
  data:
    url: http://www.europarl.europa.eu/meps/en/xml.html?query=full&filter=all
    format: XML

- title: CoE Parliamentary Assembly
  description: >
    The Council of Europe's parliamentary assembly is composed of members of
    national parliaments from European countries including Turkey and Russia.
  slug: coe_assembly
  category: pep
  publisher:
    title: Council of Europe
    url: http://www.coe.int
  url: http://www.assembly.coe.int/nw/Home-EN.asp
  data:
    url: http://www.assembly.coe.int/nw/xml/AssemblyList/MP-Alpha-EN.asp?initial=A
    format: HTML
