import pytest
from followthemoney import Statement
from followthemoney.exc import InvalidData, InvalidModel

from zavod.meta import get_catalog
from zavod.entity import Entity

TEST_DATASET = {
    "name": "test",
    "title": "Test Dataset",
    "lookups": {
        "type.country": {
            "lowercase": True,
            "options": [
                {"match": "MOORICA", "value": "us"},
            ],
        }
    },
}


def test_basic():
    catalog = get_catalog()
    test_ds = catalog.make_dataset(TEST_DATASET)
    entity = Entity(test_ds, {"schema": "Person"})
    assert len(list(entity.statements)) == 0
    entity.id = "test_entity"
    assert len(list(entity.statements)) == 1
    entity.add("name", "John Doe")
    assert len(list(entity.statements)) == 2
    entity.add("nationality", {"Britain"})
    assert len(list(entity.statements)) == 3
    entity.add("nationality", {"moorica"})
    assert len(list(entity.statements)) == 4
    assert "us" in entity.get("nationality")


def test_extra_functions():
    catalog = get_catalog()
    test_ds = catalog.make_dataset(TEST_DATASET)
    entity = Entity(test_ds, {"schema": "LegalEntity"})
    entity.id = "test_entity"

    entity.add_cast("Person", "birthDate", None)
    assert entity.schema.name == "LegalEntity"
    entity.add_cast("Person", "birthDate", "1988")
    assert entity.schema.name == "Person"
    entity.add("phone", "123456789")
    assert entity.has("phone")

    with pytest.raises(InvalidData):
        prop = entity.schema.get("identification")
        entity.unsafe_add(prop, "123456789")

    with pytest.raises(InvalidData):
        entity.add_schema("Company")

    with pytest.raises(InvalidData):
        entity.add_cast("Company", "voenCode", "72379879")

    with pytest.raises(InvalidModel):
        entity.add_cast("Banana", "peel", "Acme Inc")

    assert entity.to_dict()["properties"]["birthDate"][0] == "1988"


def test_target_logic():
    catalog = get_catalog()
    test_ds = catalog.make_dataset(TEST_DATASET)
    entity = Entity(test_ds, {"schema": "LegalEntity"})
    entity.id = "test_entity"
    assert not entity.target, entity.to_dict()

    entity.add("topics", "sanction")
    assert entity.target, entity.to_dict()


def test_external():
    catalog = get_catalog()
    test_ds = catalog.make_dataset(TEST_DATASET)
    stmt = dict(
        entity_id="ent",
        canonical_id="ent",
        schema="Person",
        dataset="test",
        first_seen="2026-07-20",
        last_seen="2026-07-20",
    )
    external_stmts = [
        Statement(prop="name", value="John Doe", external=True, **stmt),
        # A stored BASE_ID statement, as assembled from a store. It is dropped
        # by from_statements, and the synthetic one regenerated by
        # Entity.statements (always external=False) must not be counted.
        Statement(prop="id", value="abc123", external=True, **stmt),
    ]
    entity = Entity.from_statements(test_ds, external_stmts)
    assert entity.external is True

    internal_stmts = external_stmts + [
        Statement(prop="topics", value="role.rca", external=False, **stmt),
    ]
    entity = Entity.from_statements(test_ds, internal_stmts)
    assert entity.external is False
