
SELECT ?position ?positionLabel ?positionDescription ?jurisdiction ?country (COUNT(?holder) AS ?holders) WHERE {
    ?holder wdt:P39 ?position .
    # ?holder wdt:P31 wd:Q5 .
    ?holder wdt:P106 wd:Q82955 .  
    ?holder wdt:P27 wd:{{COUNTRY}} .  
    OPTIONAL { ?position wdt:P1001 ?jurisdiction }
    OPTIONAL { ?position wdt:P17 ?country }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de,es,fr". }
} GROUP BY ?position ?positionLabel ?positionDescription ?jurisdiction ?country
ORDER BY DESC(?holders)