"""
Deduplicate edge entities in the graph.

Edge entities are generated by many crawlers, so the same real-world relationship
can appear several times with slightly different dates or provenance fields. This
module creates positive resolver decisions for edge fragments that describe the
same relationship fact.

The deduper is deliberately conservative: it first buckets by schema and graph
endpoints, then keeps only unambiguous temporal candidate groups, then rejects
groups with schema-specific protected-property conflicts. Properties not listed
as protected are ignored by omission.
"""

import calendar
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import date
from typing import Dict, Iterable, List, NamedTuple, Optional, Set, Tuple

from nomenklatura import Resolver
from nomenklatura.judgement import Judgement
from nomenklatura.resolver import Identifier
from normality import slugify

from zavod.entity import Entity
from zavod.logs import get_logger
from zavod.store import View

log = get_logger(__name__)
PARTIAL_ISO_DATE = re.compile(r"^\d{4}(?:-\d{2}(?:-\d{2})?)?$")


class BucketKey(NamedTuple):
    schema: str
    source: Identifier
    target: Identifier


@dataclass(frozen=True)
class DateRange:
    start: date
    end: date
    value: str


@dataclass(frozen=True)
class TemporalValues:
    starts: Tuple[str, ...]
    ends: Tuple[str, ...]


PROTECTED_PROPS: Dict[str, List[str]] = {
    "Ownership": [
        "percentage",
        "sharesCount",
        "sharesValue",
        "sharesCurrency",
    ],
    "Directorship": ["role"],
    "Employment": ["role"],
    "Membership": ["role"],
    "Representation": ["role"],
    "Associate": ["relationship"],
    "Family": ["relationship"],
    "UnknownLink": ["role"],
    "Value": ["amount", "currency", "amountUsd"],
    "Occupancy": ["constituency", "politicalGroup", "status"],
}


def bucket_key(entity: Entity) -> Optional[BucketKey]:
    """Build the conservative candidate bucket for an edge.

    Edges are only compared inside exact-schema endpoint buckets. This prevents
    broad endpoint coincidences, such as ownership and directorship between the same
    two entities, from becoming merge candidates. Edges that cannot be represented as
    one source and one target are discarded here.
    """
    if (
        not entity.schema.edge
        or entity.schema.source_prop is None
        or entity.schema.target_prop is None
        or entity.id is None
    ):
        return None

    sources = [Identifier.get(s) for s in entity.get(entity.schema.source_prop)]
    targets = [Identifier.get(t) for t in entity.get(entity.schema.target_prop)]
    if len(sources) != 1 or len(targets) != 1:
        if sources or targets:
            log.warning(
                "Multi-ended edge", entity=entity.id, sources=sources, targets=targets
            )
        return None

    source = sources[0]
    target = targets[0]
    if source == target:
        return None
    if not entity.schema.edge_directed:
        source, target = max(source, target), min(source, target)

    return BucketKey(entity.schema.name, source, target)


def temporal_values(entity: Entity) -> TemporalValues:
    """Collect all schema-declared temporal start and end values for an edge.

    Useful when sources use more specific and less specific temporal properties
    inconsistently; values are compared as start evidence or end evidence without
    preserving the original property name.
    """
    starts: List[str] = []
    ends: List[str] = []
    for prop in entity.schema.temporal_start_props:
        starts.extend(entity.get(prop.name))
    for prop in entity.schema.temporal_end_props:
        ends.extend(entity.get(prop.name))
    return TemporalValues(tuple(sorted(set(starts))), tuple(sorted(set(ends))))


def parse_partial_iso_date(value: str) -> Optional[DateRange]:
    """Parse a partial ISO date into the range it can represent.

    Use this for temporal compatibility so `2025` can match a more precise date
    inside that year, while malformed or unsupported legacy values fall back to
    exact-value comparison elsewhere.
    """
    if not PARTIAL_ISO_DATE.match(value):
        return None

    parts = value.split("-")
    try:
        year = int(parts[0])
        if len(parts) == 1:
            return DateRange(date(year, 1, 1), date(year, 12, 31), value)

        month = int(parts[1])
        if len(parts) == 2:
            last_day = calendar.monthrange(year, month)[1]
            return DateRange(date(year, month, 1), date(year, month, last_day), value)

        day = int(parts[2])
        day_date = date(year, month, day)
        return DateRange(day_date, day_date, value)
    except ValueError:
        return None


def date_ranges_compatible(left: DateRange, right: DateRange) -> bool:
    """Check whether two parsed partial-date ranges overlap."""
    return left.start <= right.end and right.start <= left.end


def dates_compatible(left: Iterable[str], right: Iterable[str]) -> bool:
    """Check whether two temporal value sets can describe the same boundary.

    Empty sets are compatible with everything. Non-empty sets compare as partial
    ISO date ranges when possible, with exact equality as a fallback for legacy
    values.
    """
    left_values = set(left)
    right_values = set(right)
    if not left_values or not right_values:
        return True

    left_ranges = [r for r in map(parse_partial_iso_date, left_values) if r]
    right_ranges = [r for r in map(parse_partial_iso_date, right_values) if r]

    if left_ranges and right_ranges:
        return any(
            date_ranges_compatible(left_range, right_range)
            for left_range in left_ranges
            for right_range in right_ranges
        )

    # Date-typed values should normally be clean ISO dates. Fall back to exact
    # equality for any legacy values that cannot be parsed as partial ISO dates.
    return bool(left_values.intersection(right_values))


def pair_temporally_compatible(left: Entity, right: Entity) -> bool:
    """Check whether two edges have compatible start and end evidence."""
    left_values = temporal_values(left)
    right_values = temporal_values(right)
    return dates_compatible(
        left_values.starts, right_values.starts
    ) and dates_compatible(left_values.ends, right_values.ends)


def connected_components(nodes: Set[str], edges: Dict[str, Set[str]]) -> List[Set[str]]:
    """Find connected components in a small compatibility graph."""
    components: List[Set[str]] = []
    seen: Set[str] = set()
    for node in sorted(nodes):
        if node in seen:
            continue
        stack = [node]
        component: Set[str] = set()
        while stack:
            current = stack.pop()
            if current in component:
                continue
            component.add(current)
            stack.extend(edges[current] - component)
        seen.update(component)
        components.append(component)
    return components


def is_pairwise_compatible(
    group: Iterable[str], compatible: Dict[str, Set[str]]
) -> bool:
    """Check that every member of a candidate group is compatible with every other."""
    ids = list(group)
    for idx, left_id in enumerate(ids):
        for right_id in ids[idx + 1 :]:
            if right_id not in compatible[left_id]:
                return False
    return True


def temporal_candidate_groups(entities: List[Entity]) -> List[List[Entity]]:
    """Emit unambiguous temporal candidate groups from one endpoint/schema bucket.

    This prevents a vague edge, such as `2025`, from arbitrarily merging into one
    of two incompatible precise edges, such as `2025-01-01` and `2025-12-31`.
    """
    if len(entities) < 2:
        return []

    entity_by_id = {entity.id: entity for entity in entities if entity.id is not None}
    ids = set(entity_by_id)
    compatible: Dict[str, Set[str]] = {id_: set() for id_ in ids}
    incompatible: Dict[str, Set[str]] = {id_: set() for id_ in ids}

    sorted_ids = sorted(ids)
    for idx, left_id in enumerate(sorted_ids):
        for right_id in sorted_ids[idx + 1 :]:
            if pair_temporally_compatible(
                entity_by_id[left_id], entity_by_id[right_id]
            ):
                compatible[left_id].add(right_id)
                compatible[right_id].add(left_id)
            else:
                incompatible[left_id].add(right_id)
                incompatible[right_id].add(left_id)

    ambiguous: Set[str] = set()
    for id_ in ids:
        neighbors = sorted(compatible[id_])
        for idx, left_id in enumerate(neighbors):
            for right_id in neighbors[idx + 1 :]:
                if right_id in incompatible[left_id]:
                    ambiguous.add(id_)
                    break
            if id_ in ambiguous:
                break

    candidates: List[List[Entity]] = []
    remaining = ids - ambiguous
    for component in connected_components(remaining, compatible):
        if len(component) < 2:
            continue
        if not is_pairwise_compatible(component, compatible):
            log.warning("Skipping non-pairwise temporal group", entities=component)
            continue
        candidates.append([entity_by_id[id_] for id_ in sorted(component)])
    return candidates


def schema_protected_props(entity: Entity) -> List[str]:
    """Return the protected properties for the edge's most specific configured schema."""
    for schema_name, props in PROTECTED_PROPS.items():
        if entity.schema.is_a(schema_name):
            return props
    return []


def protected_values(entity: Entity, prop: str) -> Set[str]:
    """Return normalized values for a protected property."""
    values: Set[str] = set()
    for value in entity.get(prop):
        normalized = slugify(value)
        if normalized is not None:
            values.add(normalized)
    return values


def value_sets_compatible(left: Set[str], right: Set[str]) -> bool:
    """Check protected-value compatibility using empty-as-wildcard semantics."""
    if not left or not right:
        return True
    return bool(left.intersection(right))


def props_compatible(entities: List[Entity]) -> bool:
    """Reject a temporal candidate group if any protected property conflicts."""
    if not entities:
        return False

    props = schema_protected_props(entities[0])
    for prop in props:
        for idx, left in enumerate(entities):
            left_values = protected_values(left, prop)
            for right in entities[idx + 1 :]:
                right_values = protected_values(right, prop)
                if not value_sets_compatible(left_values, right_values):
                    return False
    return True


def group_edges(resolver: Resolver[Entity], view: View) -> List[List[str]]:
    """Group edge IDs that should become positive resolver decisions."""
    buckets: Dict[BucketKey, List[Entity]] = defaultdict(list)
    groups: List[List[str]] = []

    for idx, entity in enumerate(view.entities()):
        if idx > 0 and idx % 100000 == 0:
            log.info("Keyed %s entities..." % idx)

        key = bucket_key(entity)
        if key is None:
            continue
        buckets[key].append(entity)

    for entities in buckets.values():
        for group in temporal_candidate_groups(entities):
            if not props_compatible(group):
                continue
            groups.append([entity.id for entity in group if entity.id is not None])

    return groups


def merge_groups(
    resolver: Resolver[Entity], view: View, groups: List[List[str]]
) -> None:
    """Write positive resolver decisions for deduped edge groups."""
    merged_count = 0
    cluster_count = 0
    dataset_counts: Dict[str, int] = defaultdict(int)

    for values in groups:
        if len(values) == 1:
            continue

        first_id = values[0]
        first_entity = view.get_entity(first_id)
        assert first_entity is not None
        merged_count += 1
        for dataset in first_entity.datasets:
            dataset_counts[dataset] += 1

        canonical = resolver.get_canonical(first_id)
        for other_id in values[1:]:
            other_canon = resolver.get_canonical(other_id)
            if other_canon == canonical:
                continue
            other = view.get_entity(other_id)
            assert other is not None

            log.info("Merge edge: %s (%s -> %s)" % (other, other_canon, canonical))
            canonical = resolver.decide(
                canonical,
                other_canon,
                judgement=Judgement.POSITIVE,
                user="edge-dedupe",
            ).id

            merged_count += 1
            for dataset in other.datasets:
                dataset_counts[dataset] += 1

        cluster_count += 1
    log.info("Merged %s edge entities into %s clusters" % (merged_count, cluster_count))
    for dataset, count in dataset_counts.items():
        log.info("Merged %s edges in dataset %s" % (count, dataset))


def dedupe_edges(resolver: Resolver[Entity], view: View) -> None:
    """Deduplicate edge entities from a store view into resolver decisions."""
    groups = group_edges(resolver, view)
    merge_groups(resolver, view, groups)
